### PR TITLE
More linting

### PR DESCRIPTION
**Pull request by SeanKilleen**
Supports #353.

Prior to this PR: 253 files with markdown lint errors.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
Now at 233 files with markdown errors.

**Comment by SeanKilleen** [comment]
Progress: Down to 207.

**Comment by mikkelbu** [comment]
@SeanKilleen Not related to this PR, but I'll take a look at the linting errors from the analyzers. I plan to release the next version of the analyzers next week - if all goes as planned - and as part of this I think that I can remove most warnings from the analyzers.

**Comment by SeanKilleen** [comment]
@mikkelbu sounds good -- I'll create a separate issue, assign you, and link it to the original issue so that I don't forget .

**Comment by SeanKilleen** [comment]
Progress: 187 remaining.

**Comment by SeanKilleen** [comment]
158 Remaining.

**Comment by SeanKilleen** [comment]
Down to 83! Need to drop off for a bit, so merging what I have so far.

**Pull request merged**
