### PR TITLE
Retroactively document breaking change in v3.5

### LINKED ISSUE #130: Update Breaking Changes with v3.5 distribution changes
Hi,

I was trying to use nunit 3.5.0 and noticed that nunit3-console.exe was not present in the downloaded zip package (https://github.com/nunit/nunit/releases/tag/3.5), there is just the nunitlite-runner.exe. For the console you now have to download another package.
The thing is, this is a breaking change (for our scripts) which is not mentioned is the docs.

Will the future versions add back the nunit3-console.exe runner or only the lite version will be available from now one?
Why the lite runner is included but nunit3-console was moved to another package?

### PR DESCRIPTION
**Pull request by SeanKilleen**
Resolves #130.

### CODE REVIEW

**Review by CharliePoole — COMMENTED** [review]
Seems fine to me, although I haven't done such things retroactively in the past... and this is pretty old!

Note that this is in the NUnit framework docs even though it refers to the console. I'm not even a team member for that project although Chris is. I think you should ask Rob.

**Comment by SeanKilleen** [comment]
Thanks @CharliePoole! Adding @rprouse.

**Review by rprouse — COMMENTED** [review]
This isn't quite correct. The NUnit console was always in a separate package, the only thing that changed is that it stopped being released in the ZIP file that is downloaded from GitHub releases. We could document that but it was documented in the release notes here https://github.com/nunit/nunit/releases/tag/3.5 and here, https://docs.nunit.org/articles/nunit/release-notes/Pre-3.5-Release-Notes.html#nunit-35----october-3-2016. I'd say that is enough.

**Comment by SeanKilleen** [comment]
Ok, sounds good. I'll close this PR and the associated issue.

**Pull request closed without merging**
