### PR TITLE
Fix Specs menu item

### PR DESCRIPTION
**Pull request by ChrisMaddock**
This link is broken in the TOC. Is this the correct way to fix it, when a submenu is involved? I'm not totally sure, I'm afraid!

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
CI tells me that that was _not_ the right fix!

These pages are already linked under /NUnit/. Shall we just remove them from this menu?

**Comment by SeanKilleen** [comment]
@ChrisMaddock let me check into this as broken links here should have generated a warning and not made it through the build.

What's the actual behavior you're seeing? The specifications link 404s?

**Comment by ChrisMaddock** [comment]
This one seems to be generated as an empty link, with no href tag.

image

It's a second-level item under Developer Info. 🙂

**Comment by SeanKilleen** [comment]
Interesting. The `Technical Notes --> NUnit Internals --> Specifications` link goes to https://docs.nunit.org/articles/nunit/technical-notes/nunit-internals/specs/Specifications.html, which has the `uid` of `Specifications`, meaning we should be able to reference it using `xref: Specifications` in the TOC. 

I'll play around with it and see what's up but I do see the issue you're describing.

**Comment by SeanKilleen** [comment]
I figured it out; the issue is that it needs to be referenced via `topicUid` in TOC files; xref works for links in actual markdown pages. 🤷‍♂️

**Comment by ChrisMaddock** [comment]
Great - thanks for digging in to it!

**Comment by SeanKilleen** [comment]
Confirmed in my local that this is fixed. Merging. 👍

**Comment by CharliePoole** [comment]
While "fixed" in the pure bug-fixing sense, the overall problem still remains. I wonder what could be done about it.

Although part of the documentation, these items are actually __not__ documentation. They are proposals for major additions to the framework and/or engine.

At the point when I left my role as the overall project lead, I was in the process of converting or deleting all the specifications that had driven development of NUnit 3. It was no longer my job but I didn't want it to be forgotten so I created that summary page with a table to track the removal of those items. As far as I can see, nothing further happened with them.

What ought to happen IMO is for each project lead to look at the items related to that project and make a decision. 

There are a few that are still interesting to me as part of my non-NUnit work, so I'll grab copies right now. :smile:

**Comment by SeanKilleen** [comment]
@CharliePoole I treat a broken link and "what to do with items that may not actually be documentation" as separate items and suggest opening an issue to discuss it. 

I have some thoughts about these as well and I see it as part of a long term cleanup that I have yet to define, but your opinion on approach is always welcome.

**Comment by CharliePoole** [comment]
@SeanKilleen This group has conducted many "post-mortem" discussions on issues after they are closed, leading to decisions to create new ones. That's what I was trying to accomplish here. Because it's a long-term habit of ours, I didn't bother stating the obvious (to me) point that the bigger issue is entirely separate and not something you could be expected to fix in this issue. :disappointed: 

If this goes as other such discussions have gone, we'll end up with one or more issues in the proper projects. I hope.

**Comment by SeanKilleen** [comment]
@CharliePoole I prefer to have that discussion in a separate issue that references this issue to keep things clean. That discussion can then have agreed upon action items that come out of it. I'll probably add a bot to lock closed issues to make that approach less confusing / ambiguous. 👍

**Comment by CharliePoole** [comment]
In that case, I'll stop doing it in this project!

**Comment by SeanKilleen** [comment]
To be clear, I absolutely love the follow-up; I just prefer it to be in a new issue where it can be addressed holistically rather than an already-closed issue.

**Pull request merged**
