### PR TITLE
Add GitHub Codespaces configuration

### PR DESCRIPTION
**Pull request by SeanKilleen**
Adds GitHub Codespaces default configuration for people to use.
## Goal

Allow someone like @CharliePoole the ability to click a button from GitHub and bring up a VS Code instance in the browser with all the extensions and tooling needed to quickly build and test the docs. Without ever having to leave the browser.

This first pass will be to get it working. Future changes will aim to do things like automatically build things in the container on startup and watch / rebuild on changes.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
So far:

✅ Can open a codespace
✅ Can see the files
✅ Can modify files in the codespace
✅ Can run `docfx build` and `docfx serve` within the codebase
❌ Can't actually open the forwarded port `8080` site as expected.

**Comment by CharliePoole** [comment]
This will be quite cool if you can make it  work!

**Comment by SeanKilleen** [comment]
FYI, I created a GitHub Discussion to attempt to troubleshoot the issue with `docfx serve` not showing up: https://github.com/github/feedback/discussions/4070

I was able to open this branch in this container in VS Code on my machine and have it work as expected.

While I'm waiting for this, I'll probably try to add some shortcuts to commands to make them available within the codespace, so that we can run `spellcheck` or `lint` or `test` and get the expected behavior so we can get a smaller feedback loop in the IDE.

**Comment by SeanKilleen** [comment]
@CharliePoole @ChrisMaddock I'm pleased to report that I've figured it out and GitHub Codespaces is now functioning for NUnit docs. 

Following the instructions in the `README` once I merge it, you should be able to open the repo in codespaces and run the commands there to do everything in-browser.

**Pull request merged**
