### PR TITLE
WIP: Add programmatic constraint examples & surface in docs

### PR DESCRIPTION
**Pull request by SeanKilleen**
Supports #794.

Starting with the low-hanging fruit first. Getting the table cleaned up, getting some basic examples into programmatic format, and seeing how to best surface them in the main list.

### CODE REVIEW

**Review by SeanKilleen — COMMENTED** [review]
Hmm, a bit of a bummer on the main page front. I was hoping to show the same programmatic snippets in a column using the same code that displays on the page itself. But this is a bit too far a stretch for docfx or similar editors. 

So, I think for now, for each constraint I'll aim to get:

* A programmatic example in snippets within the article
* Pseudo-code examples in the `Quick example` column.

**Comment by SeanKilleen** [comment]
Ping @OsirisTerje just to make sure I'm going about this in an OK way in line with how we talked about it. I think I'm in the right spot but better to ask earlier than later. :)

**Review by OsirisTerje — APPROVED** [review]
LVGTM

**Comment by OsirisTerje** [comment]
@SeanKilleen Sorry, was a bit too fast there :-)  Shame on me.   Branch restored, so please continue ----

**Pull request merged**
