### PR TITLE
Split Test Adapter V4 release notes into separate page

### PR DESCRIPTION
**Pull request by TyMick**
The page being called "Release Notes V3" in the table of contents made it difficult for me to find the V4 release notes for a while.

This PR also explicitly mentions the version number in each release notes file name, to make it more difficult to forget to create a new file for the next major version's release notes (the previous V3 release notes file was just named `Adapter-Release-Notes.md`).

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=602) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=602) before we can accept your contribution.<br/><br/>:x: TyMick [sign now](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=602)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/docs?pullRequest=602) it.</sub>

**Comment by TyMick** [comment]
I'll go make sure I've got employer permission for that CLA. 👍🏼

**Comment by TyMick** [comment]
I fiddled with things and found a way to add a client-side redirect that works when I build locally. Would that be nice to have?

**Comment by SeanKilleen** [comment]
@TyMick can't hurt! :)

**Pull request merged**
