### PR TITLE
docs: add missing parenthesis

### PR DESCRIPTION
**Pull request by kevinpearce**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=690) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=690) before we can accept your contribution.<br/><br/>:x: kevinpearce [sign now](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=690)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/docs?pullRequest=690) it.</sub>

**Review by mikkelbu — APPROVED** [review]
The change looks good to me, but I also found a couple of other problems on this page that we also could fix. Either we can include them here (if you want to do it or we can do it in another PR)

Line 95 missing `"` before `World`
Line 115 `later. Is` should be `later, Is` (so change `.` to `,`)
Line 146-147 the type is not `int`. We should either use `var` or the correct explicit type

**Comment by SeanKilleen** [comment]
Thanks @kevinpearce! These changes look good to me. I'm going to pause on the merge but only because the builds are failing due to #687 (our docfx-action container picked up a git security patch that is causing issues for us and others in the ecosystem).

I'll merge this once I get the build working again (hopefully today). In the meantime, feel free to address any of @mikkelbu's additional ideas; otherwise, I'll note and tackle them separately.

**Comment by kevinpearce** [comment]
A further commit pushed to address further issues raised above.
Kept with explicit types for consistency.

**Review by mikkelbu — APPROVED** [review]
Thanks for this contribution @kevinpearce 👍. It is much appreciated

**Review by SeanKilleen — APPROVED** [review]
Thank you for this, @kevinpearce!

**Pull request merged**
