### PR TITLE
Make documentation up-2-date wrt. help information

### PR DESCRIPTION
**Pull request by mikkelbu**
Fixes nunit/nunit#3433

### CODE REVIEW

**Review by CharliePoole — APPROVED** [review]

**Comment by CharliePoole** [comment]
LGTM One comment though...

The relationship among `--test`, `--where` and `--prefilter` isn't really clear from just reading this. What about a note following all the options explaining that?

**Review by SeanKilleen — APPROVED** [review]
@mikkelbu LGTM. Thanks for this!

Let me know if you want to address Charlie's recommendation as part of this PR or another; if you'd prefer to do it separately I'll merge this as-is.

**Comment by CharliePoole** [comment]
@mikkelbu Would you like me to add something?

**Comment by mikkelbu** [comment]
> @mikkelbu Would you like me to add something?

Please do. You are most welcome to add to this PR.

**Comment by CharliePoole** [comment]
@mikkelbu Take a look at my additions and merge if it looks OK to you - or change as needed.

**Comment by mikkelbu** [comment]
@CharliePoole I like the change. I was consider whether we should make it even more explicit that a consequence of prefiltering is that unspecified TestCaseSources, ValueSource ... are not run. I'm unsure if the regular user understands the exact consequences of "If specified, it limits the classes, which NUnit will examine to find tests.". By we can also merge this as it is, and then I'll create an issue for a page for prefiltering that we also can link to.

Ps. I cannot merge the PR as I don't have the rights (I think that only the administrators and @SeanKilleen can do this, at least I know that both I and @OsirisTerje don't have write rights). I'll ping @rprouse/you about this on slack.

**Comment by SeanKilleen** [comment]
@mikkelbu yeah we'll need to get you those rights ASAP. Sorry it's taken so long.

For now, I'll merge. 👍

**Pull request merged**
