### PR TITLE
Prepare release notes for NUNit3Testadapter 4.0.0-beta.1

### PR DESCRIPTION
**Pull request by OsirisTerje**

### CODE REVIEW

**Review by SeanKilleen — APPROVED** [review]
👍 LGTM other than markdown linting issues etc.

Feel free to merge once those are resolved or ping me for the merge. Thanks!

**Comment by OsirisTerje** [comment]
@SeanKilleen The linter reacts to this:  [netcorefactory](https://github.com/netcorefactory)   Which is really not good.-....  Strange that it doesn't react to the same in the release notes.

**Comment by SeanKilleen** [comment]
@OsirisTerje I just pushed a change that adds it to the ignored words in cSpell.json -- I'll see if I can add some additional output when things fail on the spellcheck to refer folks to that file.

**Comment by OsirisTerje** [comment]
Thanks!  It is strange it reacted to it there, and not in the release notes which is full of these references too.  It should probably not react to anything that is in ``` [  ](  )```, but not sure how easy that is....

**Comment by SeanKilleen** [comment]
@OsirisTerje I tried it a few times and had to abandon that particular one. There's an `ignoreRegExpList` in `cSpell.json` that exempts some other items and I encourage anyone to take a shot at it. :)

**Comment by OsirisTerje** [comment]
ahm....  * You’re not authorized to merge this pull request.*   ... could you,..please ?

**Pull request merged**
