### PR TITLE
Update EqualConstraint.md

### PR DESCRIPTION
**Pull request by borro0**
Fixed typo .WithIn(amount) -> .Within(amount)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Review by SeanKilleen — APPROVED** [review]
Thank you!

**Comment by borro0** [comment]
Something wrong with the pipeline?

**Review by SeanKilleen — APPROVED** [review]
Thanks for this contribution! 🎉

**Comment by SeanKilleen** [comment]
> Something wrong with the pipeline?

Currently yes unfortunately. There's a step to generate Netlify previews for the docs and it's flaky due to a permissions issue that I haven't sorted yet. It's nice when it works but it is not nearly consistent enough.

**Pull request merged**
